### ISSUE TITLE
선택 페이지 제작 

### ISSUE THREAD

**Issue by kmyobin** [kmyobin/Can_I_Eat#7]
### 📝 Description
선택 페이지 제작 
![image](https://user-images.githubusercontent.com/64712993/231807532-9cb7d470-4ba6-4efd-8f68-ec150f706920.png)
### 💻 Todo
- [x] 알레르기 리스트 UI 구현
- [x] 선택된 알레르기 리스트 UI 구현
- [x] 버튼 구현
- [x] 모바일 환경 UI 구현
- [x] 이벤트 처리
- [ ] 알레르기 관련 정보 추가 (2023.04.24 이후 진행 예정)

### 🖼 결과
![image](https://user-images.githubusercontent.com/64712993/233692533-da9d3daf-0018-43a4-84f4-9ef9840238d3.png)
![image](https://user-images.githubusercontent.com/64712993/233692549-2695490b-4498-48aa-9060-c12d082ecd0b.png)
![image](https://user-images.githubusercontent.com/64712993/233692567-3b884bd7-43ea-473d-be02-13750b1bd7f1.png)
![image](https://user-images.githubusercontent.com/64712993/233692577-a379d15e-80ee-47e7-bdbf-70f815e09383.png)
